export interface ARTICLES_LIST_SCHEMA {
    id: number,
    date: string,
    date_gmt: string,
    modified: string,
    modified_gmt: string,
    slug: string,
    status: string,
    type: string,
    link: string,
    author: number,
    featured_media: number,
    comment_status: string,
    ping_status: string,
    sticky: boolean,
    template: string,
}
